/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandupRouteImport } from './routes/standup'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ChatInstanceIdRouteImport } from './routes/chat.$instanceId'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiStatsProxyRouteImport } from './routes/api/stats-proxy'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiSpawnRouteImport } from './routes/api/spawn'
import { Route as ApiInstancesRouteImport } from './routes/api/instances'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiGatewayProxyRouteImport } from './routes/api/gateway-proxy'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api/tasks.$taskId'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime/session'
import { Route as ApiInstancesIdRouteImport } from './routes/api/instances.$id'

const StandupRoute = StandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatInstanceIdRoute = ChatInstanceIdRouteImport.update({
  id: '/chat/$instanceId',
  path: '/chat/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsProxyRoute = ApiStatsProxyRouteImport.update({
  id: '/api/stats-proxy',
  path: '/api/stats-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpawnRoute = ApiSpawnRouteImport.update({
  id: '/api/spawn',
  path: '/api/spawn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstancesRoute = ApiInstancesRouteImport.update({
  id: '/api/instances',
  path: '/api/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayProxyRoute = ApiGatewayProxyRouteImport.update({
  id: '/api/gateway-proxy',
  path: '/api/gateway-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime/session',
  path: '/api/realtime/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstancesIdRoute = ApiInstancesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInstancesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/debug': typeof DebugRoute
  '/instances': typeof InstancesRoute
  '/office': typeof OfficeRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/standup': typeof StandupRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/gateway-proxy': typeof ApiGatewayProxyRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/instances': typeof ApiInstancesRouteWithChildren
  '/api/spawn': typeof ApiSpawnRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/stats-proxy': typeof ApiStatsProxyRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/chat/$instanceId': typeof ChatInstanceIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/instances/$id': typeof ApiInstancesIdRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/debug': typeof DebugRoute
  '/instances': typeof InstancesRoute
  '/office': typeof OfficeRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/standup': typeof StandupRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/gateway-proxy': typeof ApiGatewayProxyRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/instances': typeof ApiInstancesRouteWithChildren
  '/api/spawn': typeof ApiSpawnRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/stats-proxy': typeof ApiStatsProxyRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/chat/$instanceId': typeof ChatInstanceIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/instances/$id': typeof ApiInstancesIdRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/debug': typeof DebugRoute
  '/instances': typeof InstancesRoute
  '/office': typeof OfficeRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/standup': typeof StandupRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/gateway-proxy': typeof ApiGatewayProxyRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/instances': typeof ApiInstancesRouteWithChildren
  '/api/spawn': typeof ApiSpawnRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/stats-proxy': typeof ApiStatsProxyRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/chat/$instanceId': typeof ChatInstanceIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/instances/$id': typeof ApiInstancesIdRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/debug'
    | '/instances'
    | '/office'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/standup'
    | '/api/agents'
    | '/api/gateway-proxy'
    | '/api/insights'
    | '/api/instances'
    | '/api/spawn'
    | '/api/stats'
    | '/api/stats-proxy'
    | '/api/tasks'
    | '/chat/$instanceId'
    | '/tasks/$taskId'
    | '/api/instances/$id'
    | '/api/realtime/session'
    | '/api/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/debug'
    | '/instances'
    | '/office'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/standup'
    | '/api/agents'
    | '/api/gateway-proxy'
    | '/api/insights'
    | '/api/instances'
    | '/api/spawn'
    | '/api/stats'
    | '/api/stats-proxy'
    | '/api/tasks'
    | '/chat/$instanceId'
    | '/tasks/$taskId'
    | '/api/instances/$id'
    | '/api/realtime/session'
    | '/api/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/debug'
    | '/instances'
    | '/office'
    | '/setup'
    | '/sign-in'
    | '/sign-up'
    | '/standup'
    | '/api/agents'
    | '/api/gateway-proxy'
    | '/api/insights'
    | '/api/instances'
    | '/api/spawn'
    | '/api/stats'
    | '/api/stats-proxy'
    | '/api/tasks'
    | '/chat/$instanceId'
    | '/tasks/$taskId'
    | '/api/instances/$id'
    | '/api/realtime/session'
    | '/api/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DebugRoute: typeof DebugRoute
  InstancesRoute: typeof InstancesRoute
  OfficeRoute: typeof OfficeRoute
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StandupRoute: typeof StandupRoute
  ApiAgentsRoute: typeof ApiAgentsRoute
  ApiGatewayProxyRoute: typeof ApiGatewayProxyRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiInstancesRoute: typeof ApiInstancesRouteWithChildren
  ApiSpawnRoute: typeof ApiSpawnRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiStatsProxyRoute: typeof ApiStatsProxyRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
  ChatInstanceIdRoute: typeof ChatInstanceIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standup': {
      id: '/standup'
      path: '/standup'
      fullPath: '/standup'
      preLoaderRoute: typeof StandupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$instanceId': {
      id: '/chat/$instanceId'
      path: '/chat/$instanceId'
      fullPath: '/chat/$instanceId'
      preLoaderRoute: typeof ChatInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats-proxy': {
      id: '/api/stats-proxy'
      path: '/api/stats-proxy'
      fullPath: '/api/stats-proxy'
      preLoaderRoute: typeof ApiStatsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spawn': {
      id: '/api/spawn'
      path: '/api/spawn'
      fullPath: '/api/spawn'
      preLoaderRoute: typeof ApiSpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instances': {
      id: '/api/instances'
      path: '/api/instances'
      fullPath: '/api/instances'
      preLoaderRoute: typeof ApiInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-proxy': {
      id: '/api/gateway-proxy'
      path: '/api/gateway-proxy'
      fullPath: '/api/gateway-proxy'
      preLoaderRoute: typeof ApiGatewayProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/realtime/session': {
      id: '/api/realtime/session'
      path: '/api/realtime/session'
      fullPath: '/api/realtime/session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instances/$id': {
      id: '/api/instances/$id'
      path: '/$id'
      fullPath: '/api/instances/$id'
      preLoaderRoute: typeof ApiInstancesIdRouteImport
      parentRoute: typeof ApiInstancesRoute
    }
  }
}

interface ApiInstancesRouteChildren {
  ApiInstancesIdRoute: typeof ApiInstancesIdRoute
}

const ApiInstancesRouteChildren: ApiInstancesRouteChildren = {
  ApiInstancesIdRoute: ApiInstancesIdRoute,
}

const ApiInstancesRouteWithChildren = ApiInstancesRoute._addFileChildren(
  ApiInstancesRouteChildren,
)

interface ApiTasksRouteChildren {
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksTaskIdRoute: ApiTasksTaskIdRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DebugRoute: DebugRoute,
  InstancesRoute: InstancesRoute,
  OfficeRoute: OfficeRoute,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StandupRoute: StandupRoute,
  ApiAgentsRoute: ApiAgentsRoute,
  ApiGatewayProxyRoute: ApiGatewayProxyRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiInstancesRoute: ApiInstancesRouteWithChildren,
  ApiSpawnRoute: ApiSpawnRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiStatsProxyRoute: ApiStatsProxyRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
  ChatInstanceIdRoute: ChatInstanceIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
