/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandupRouteImport } from './routes/standup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiSpawnRouteImport } from './routes/api/spawn'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api/tasks.$taskId'
import { Route as ApiRealtimeSessionRouteImport } from './routes/api/realtime/session'

const StandupRoute = StandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpawnRoute = ApiSpawnRouteImport.update({
  id: '/api/spawn',
  path: '/api/spawn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime/session',
  path: '/api/realtime/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/standup': typeof StandupRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/spawn': typeof ApiSpawnRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/standup': typeof StandupRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/spawn': typeof ApiSpawnRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/standup': typeof StandupRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/insights': typeof ApiInsightsRoute
  '/api/spawn': typeof ApiSpawnRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/standup'
    | '/api/agents'
    | '/api/insights'
    | '/api/spawn'
    | '/api/stats'
    | '/api/tasks'
    | '/tasks/$taskId'
    | '/api/realtime/session'
    | '/api/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/standup'
    | '/api/agents'
    | '/api/insights'
    | '/api/spawn'
    | '/api/stats'
    | '/api/tasks'
    | '/tasks/$taskId'
    | '/api/realtime/session'
    | '/api/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/standup'
    | '/api/agents'
    | '/api/insights'
    | '/api/spawn'
    | '/api/stats'
    | '/api/tasks'
    | '/tasks/$taskId'
    | '/api/realtime/session'
    | '/api/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StandupRoute: typeof StandupRoute
  ApiAgentsRoute: typeof ApiAgentsRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
  ApiSpawnRoute: typeof ApiSpawnRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standup': {
      id: '/standup'
      path: '/standup'
      fullPath: '/standup'
      preLoaderRoute: typeof StandupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spawn': {
      id: '/api/spawn'
      path: '/api/spawn'
      fullPath: '/api/spawn'
      preLoaderRoute: typeof ApiSpawnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/realtime/session': {
      id: '/api/realtime/session'
      path: '/api/realtime/session'
      fullPath: '/api/realtime/session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiTasksRouteChildren {
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksTaskIdRoute: ApiTasksTaskIdRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StandupRoute: StandupRoute,
  ApiAgentsRoute: ApiAgentsRoute,
  ApiInsightsRoute: ApiInsightsRoute,
  ApiSpawnRoute: ApiSpawnRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
  TasksTaskIdRoute: TasksTaskIdRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
